import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { SanityLive } from '@/sanity/lib/live'
import { DisableDraftMode } from './components/disable-draft-mode';
import { draftMode } from "next/headers";
import { VisualEditing } from 'next-sanity/visual-editing';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const { isEnabled } = await draftMode();
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <SanityLive />
        {isEnabled &&
          <>
            <VisualEditing />
            <DisableDraftMode />
          </>
        }
      </body>
    </html>
  );
}